name: Run Spider

on:
  workflow_dispatch:
    # Allow manual triggering

# Add permissions configuration
permissions:
  contents: write

jobs:
  spider:
    runs-on: ubuntu-latest
    env:
      PROVIDER_API_KEY: ${{ secrets.PROVIDER_API_KEY }}
      PROVIDER_BASE_URL: ${{ vars.PROVIDER_BASE_URL }}
      PROVIDER_MODEL_ID: ${{ vars.PROVIDER_MODEL_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run spider
        run: bun run spider
